export const cardsOptions = [
  {
    code: 1000,
    day: "Sunny",
    night: "Clear",
    imgDay: "sun.png",
    imgNight: "night.png",
    bg_night_from: "from-indigo-500",
    bg_night_to: "to-indigo-800",
    bg_day_from: "from-yellow-200",
    bg_day_to: "to-amber-400",
    icon: 113,
  },
  {
    code: 1003,
    day: "Partly cloudy",
    night: "Partly cloudy",
    imgDay: "partly-cloudy-rain-day.png",
    imgNight: "partly-cloudy-rain-night.png",
    bg_night_from: "from-indigo-500",
    bg_night_to: "to-indigo-800",
    bg_day_from: "from-yellow-200",
    bg_day_to: "to-amber-400",
    icon: 116,
  },
  {
    code: 1006,
    day: "Cloudy",
    night: "Cloudy",
    imgDay: "cloudy.png",
    imgNight: "cloudy.png",
    bg_night_from: "from-indigo-500",
    bg_night_to: "to-indigo-800",
    bg_day_from: "from-yellow-200",
    bg_day_to: "to-amber-400",
    icon: 119,
  },
  {
    code: 1009,
    day: "Overcast",
    night: "Overcast",
    imgDay: "cloud-and-fog.png",
    imgNight: "cloud-and-fog.png",
    bg_night_from: "from-indigo-500",
    bg_night_to: "to-indigo-800",
    bg_day_from: "from-yellow-200",
    bg_day_to: "to-amber-400",
    icon: 122,
  },
  {
    code: 1030,
    day: "Mist",
    night: "Mist",
    imgDay: "cloud-and-fog.png",
    imgNight: "cloud-and-fog.png",
    bg_night_from: "from-indigo-500",
    bg_night_to: "to-indigo-800",
    bg_day_from: "from-yellow-200",
    bg_day_to: "to-amber-400",
    icon: 143,
  },
  {
    code: 1063,
    day: "Patchy rain possible",
    night: "Patchy rain possible",
    imgDay: "raining-day.png",
    imgNight: "raining-night.png",
    bg_night_from: "from-indigo-500",
    bg_night_to: "to-indigo-800",
    bg_day_from: "from-yellow-200",
    bg_day_to: "to-amber-400",
    icon: 176,
  },
  {
    code: 1066,
    day: "Patchy snow possible",
    night: "Patchy snow possible",
    imgDay: "snow-rain.png",
    imgNight: "snow-rain.png",
    bg_night_from: "from-indigo-500",
    bg_night_to: "to-indigo-800",
    bg_day_from: "from-yellow-200",
    bg_day_to: "to-amber-400",
    icon: 179,
  },
  {
    code: 1069,
    day: "Patchy sleet possible",
    night: "Patchy sleet possible",
    imgDay: "raining-day.png",
    imgNight: "raining-night.png",
    bg_night_from: "from-indigo-500",
    bg_night_to: "to-indigo-800",
    bg_day_from: "from-yellow-200",
    bg_day_to: "to-amber-400",
    icon: 182,
  },
  {
    code: 1072,
    day: "Patchy freezing drizzle possible",
    night: "Patchy freezing drizzle possible",
    imgDay: "raining-day.png",
    imgNight: "raining-night.png",
    bg_night_from: "from-indigo-500",
    bg_night_to: "to-indigo-800",
    bg_day_from: "from-yellow-200",
    bg_day_to: "to-amber-400",
    icon: 185,
  },
  {
    code: 1087,
    day: "Thundery outbreaks possible",
    night: "Thundery outbreaks possible",
    imgDay: "lighting-and-cloudy.png",
    imgNight: "lighting-and-cloudy.png",
    bg_night_from: "from-indigo-500",
    bg_night_to: "to-indigo-800",
    bg_day_from: "from-yellow-200",
    bg_day_to: "to-amber-400",
    icon: 200,
  },
  {
    code: 1114,
    day: "Blowing snow",
    night: "Blowing snow",
    imgDay: "snow.png",
    imgNight: "snow.png",
    bg_night_from: "from-indigo-500",
    bg_night_to: "to-indigo-800",
    bg_day_from: "from-yellow-200",
    bg_day_to: "to-amber-400",
    icon: 227,
  },
  {
    code: 1117,
    day: "Blizzard",
    night: "Blizzard",
    imgDay: "snow.png",
    imgNight: "snow.png",
    bg_night_from: "from-indigo-500",
    bg_night_to: "to-indigo-800",
    bg_day_from: "from-yellow-200",
    bg_day_to: "to-amber-400",
    icon: 230,
  },
  {
    code: 1135,
    day: "Fog",
    night: "Fog",
    imgDay: "cloud-and-fog.png",
    imgNight: "cloud-and-fog.png",
    bg_night_from: "from-indigo-500",
    bg_night_to: "to-indigo-800",
    bg_day_from: "from-yellow-200",
    bg_day_to: "to-amber-400",
    icon: 248,
  },
  {
    code: 1147,
    day: "Freezing fog",
    night: "Freezing fog",
    imgDay: "cloud-and-fog.png",
    imgNight: "cloud-and-fog.png",
    bg_night_from: "from-indigo-500",
    bg_night_to: "to-indigo-800",
    bg_day_from: "from-yellow-200",
    bg_day_to: "to-amber-400",
    icon: 260,
  },
  {
    code: 1150,
    day: "Patchy light drizzle",
    night: "Patchy light drizzle",
    imgDay: "raining-day.png",
    imgNight: "raining-night.png",
    bg_night_from: "from-indigo-500",
    bg_night_to: "to-indigo-800",
    bg_day_from: "from-yellow-200",
    bg_day_to: "to-amber-400",
    icon: 263,
  },
  {
    code: 1153,
    day: "Light drizzle",
    night: "Light drizzle",
    imgDay: "raining-day.png",
    imgNight: "raining-night.png",
    bg_night_from: "from-indigo-500",
    bg_night_to: "to-indigo-800",
    bg_day_from: "from-yellow-200",
    bg_day_to: "to-amber-400",
    icon: 266,
  },
  {
    code: 1168,
    day: "Freezing drizzle",
    night: "Freezing drizzle",
    imgDay: "heavy-rain.png",
    imgNight: "heavy-rain.png",
    bg_night_from: "from-indigo-500",
    bg_night_to: "to-indigo-800",
    bg_day_from: "from-yellow-200",
    bg_day_to: "to-amber-400",
    icon: 281,
  },
  {
    code: 1171,
    day: "Heavy freezing drizzle",
    night: "Heavy freezing drizzle",
    imgDay: "heavy-rain.png",
    imgNight: "heavy-rain.png",
    bg_night_from: "from-neutral-300",
    bg_night_to: "to-gray-700",
    bg_day_from: "from-neutral-300",
    bg_day_to: "to-gray-700",
    icon: 284,
  },
  {
    code: 1180,
    day: "Patchy light rain",
    night: "Patchy light rain",
    imgDay: "raining-day.png",
    imgNight: "raining-night.png",
    bg_night_from: "from-indigo-500",
    bg_night_to: "to-indigo-800",
    bg_day_from: "from-yellow-200",
    bg_day_to: "to-amber-400",
    icon: 293,
  },
  {
    code: 1183,
    day: "Light rain",
    night: "Light rain",
    imgDay: "raining-day.png",
    imgNight: "raining-night.png",
    bg_night_from: "from-indigo-500",
    bg_night_to: "to-indigo-800",
    bg_day_from: "from-yellow-200",
    bg_day_to: "to-amber-400",
    icon: 296,
  },
  {
    code: 1186,
    day: "Moderate rain at times",
    night: "Moderate rain at times",
    imgDay: "raining-day.png",
    imgNight: "raining-night.png",
    bg_night_from: "from-indigo-500",
    bg_night_to: "to-indigo-800",
    bg_day_from: "from-yellow-200",
    bg_day_to: "to-amber-400",
    icon: 299,
  },
  {
    code: 1189,
    day: "Moderate rain",
    night: "Moderate rain",
    imgDay: "raining-day.png",
    imgNight: "raining-night.png",
    bg_night_from: "from-indigo-500",
    bg_night_to: "to-indigo-800",
    bg_day_from: "from-yellow-200",
    bg_day_to: "to-amber-400",
    icon: 302,
  },
  {
    code: 1192,
    day: "Heavy rain at times",
    night: "Heavy rain at times",
    imgDay: "heavy-rain.png",
    imgNight: "heavy-rain.png",
    bg_night_from: "from-neutral-300",
    bg_night_to: "to-gray-700",
    bg_day_from: "from-neutral-300",
    bg_day_to: "to-gray-700",
    icon: 305,
  },
  {
    code: 1195,
    day: "Heavy rain",
    night: "Heavy rain",
    imgDay: "heavy-rain.png",
    imgNight: "heavy-rain.png",
    bg_night_from: "from-neutral-300",
    bg_night_to: "to-gray-700",
    bg_day_from: "from-neutral-300",
    bg_day_to: "to-gray-700",
    icon: 308,
  },
  {
    code: 1198,
    day: "Light freezing rain",
    night: "Light freezing rain",
    imgDay: "snow-rain.png",
    imgNight: "snow-rain.png",
    bg_night_from: "from-cyan-200",
    bg_night_to: "to-blue-700",
    bg_day_from: "from-cyan-200",
    bg_day_to: "to-blue-700",
    icon: 311,
  },
  {
    code: 1201,
    day: "Moderate or heavy freezing rain",
    night: "Moderate or heavy freezing rain",
    imgDay: "snow-rain.png",
    imgNight: "snow-rain.png",
    bg_night_from: "from-cyan-200",
    bg_night_to: "to-blue-700",
    bg_day_from: "from-cyan-200",
    bg_day_to: "to-blue-700",
    icon: 314,
  },
  {
    code: 1204,
    day: "Light sleet",
    night: "Light sleet",
    imgDay: "snow-rain.png",
    imgNight: "snow-rain.png",
    bg_night_from: "from-cyan-200",
    bg_night_to: "to-blue-700",
    bg_day_from: "from-cyan-200",
    bg_day_to: "to-blue-700",
    icon: 317,
  },
  {
    code: 1207,
    day: "Moderate or heavy sleet",
    night: "Moderate or heavy sleet",
    imgDay: "snow-rain.png",
    imgNight: "snow-rain.png",
    bg_night_from: "from-cyan-200",
    bg_night_to: "to-blue-700",
    bg_day_from: "from-cyan-200",
    bg_day_to: "to-blue-700",
    icon: 320,
  },
  {
    code: 1210,
    day: "Patchy light snow",
    night: "Patchy light snow",
    imgDay: "snow-rain.png",
    imgNight: "snow-rain.png",
    bg_night_from: "from-cyan-200",
    bg_night_to: "to-blue-700",
    bg_day_from: "from-cyan-200",
    bg_day_to: "to-blue-700",
    icon: 323,
  },
  {
    code: 1213,
    day: "Light snow",
    night: "Light snow",
    imgDay: "snow-rain.png",
    imgNight: "snow-rain.png",
    bg_night_from: "from-cyan-200",
    bg_night_to: "to-blue-700",
    bg_day_from: "from-cyan-200",
    bg_day_to: "to-blue-700",
    icon: 326,
  },
  {
    code: 1216,
    day: "Patchy moderate snow",
    night: "Patchy moderate snow",
    imgDay: "snow-rain.png",
    imgNight: "snow-rain.png",
    bg_night_from: "from-cyan-200",
    bg_night_to: "to-blue-700",
    bg_day_from: "from-cyan-200",
    bg_day_to: "to-blue-700",
    icon: 329,
  },
  {
    code: 1219,
    day: "Moderate snow",
    night: "Moderate snow",
    imgDay: "snow-rain.png",
    imgNight: "snow-rain.png",
    bg_night_from: "from-cyan-200",
    bg_night_to: "to-blue-700",
    bg_day_from: "from-cyan-200",
    bg_day_to: "to-blue-700",
    icon: 332,
  },
  {
    code: 1222,
    day: "Patchy heavy snow",
    night: "Patchy heavy snow",
    imgDay: "snow-rain.png",
    imgNight: "snow-rain.png",
    bg_night_from: "from-cyan-200",
    bg_night_to: "to-blue-700",
    bg_day_from: "from-cyan-200",
    bg_day_to: "to-blue-700",
    icon: 335,
  },
  {
    code: 1225,
    day: "Heavy snow",
    night: "Heavy snow",
    imgDay: "snow-rain.png",
    imgNight: "snow-rain.png",
    bg_night_from: "from-cyan-200",
    bg_night_to: "to-blue-700",
    bg_day_from: "from-cyan-200",
    bg_day_to: "to-blue-700",
    icon: 338,
  },
  {
    code: 1237,
    day: "Ice pellets",
    night: "Ice pellets",
    imgDay: "snow-rain.png",
    imgNight: "snow-rain.png",
    bg_night_from: "from-cyan-200",
    bg_night_to: "to-blue-700",
    bg_day_from: "from-cyan-200",
    bg_day_to: "to-blue-700",
    icon: 350,
  },
  {
    code: 1240,
    day: "Light rain shower",
    night: "Light rain shower",
    imgDay: "partly-cloudy-rain-day.png",
    imgNight: "partly-cloudy-rain-night.png",
    bg_night_from: "from-cyan-200",
    bg_night_to: "to-blue-700",
    bg_day_from: "from-cyan-200",
    bg_day_to: "to-blue-700",
    icon: 353,
  },
  {
    code: 1243,
    day: "Moderate or heavy rain shower",
    night: "Moderate or heavy rain shower",
    imgDay: "partly-cloudy-rain-day.png",
    imgNight: "partly-cloudy-rain-night.png",
    bg_night_from: "from-neutral-300",
    bg_night_to: "to-gray-700",
    bg_day_from: "from-neutral-300",
    bg_day_to: "to-gray-700",
    icon: 356,
  },
  {
    code: 1246,
    day: "Torrential rain shower",
    night: "Torrential rain shower",
    imgDay: "heavy-rain.png",
    imgNight: "heavy-rain.png",
    bg_night_from: "from-neutral-300",
    bg_night_to: "to-gray-700",
    bg_day_from: "from-neutral-300",
    bg_day_to: "to-gray-700",
    icon: 359,
  },
  {
    code: 1249,
    day: "Light sleet showers",
    night: "Light sleet showers",
    imgDay: "snow-rain.png",
    imgNight: "snow-rain.png",
    bg_night_from: "from-cyan-200",
    bg_night_to: "to-blue-700",
    bg_day_from: "from-cyan-200",
    bg_day_to: "to-blue-700",
    icon: 362,
  },
  {
    code: 1252,
    day: "Moderate or heavy sleet showers",
    night: "Moderate or heavy sleet showers",
    imgDay: "snow-rain.png",
    imgNight: "snow-rain.png",
    bg_night_from: "from-cyan-200",
    bg_night_to: "to-blue-700",
    bg_day_from: "from-cyan-200",
    bg_day_to: "to-blue-700",
    icon: 365,
  },
  {
    code: 1255,
    day: "Light snow showers",
    night: "Light snow showers",
    imgDay: "snow-rain.png",
    imgNight: "snow-rain.png",
    bg_night_from: "from-cyan-200",
    bg_night_to: "to-blue-700",
    bg_day_from: "from-cyan-200",
    bg_day_to: "to-blue-700",
    icon: 368,
  },
  {
    code: 1258,
    day: "Moderate or heavy snow showers",
    night: "Moderate or heavy snow showers",
    imgDay: "snow-rain.png",
    imgNight: "snow-rain.png",
    bg_night_from: "from-cyan-200",
    bg_night_to: "to-blue-700",
    bg_day_from: "from-cyan-200",
    bg_day_to: "to-blue-700",
    icon: 371,
  },
  {
    code: 1261,
    day: "Light showers of ice pellets",
    night: "Light showers of ice pellets",
    imgDay: "snow-rain.png",
    imgNight: "snow-rain.png",
    bg_night_from: "from-neutral-300",
    bg_night_to: "to-gray-700",
    bg_day_from: "from-neutral-300",
    bg_day_to: "to-gray-700",
    icon: 374,
  },
  {
    code: 1264,
    day: "Moderate or heavy showers of ice pellets",
    night: "Moderate or heavy showers of ice pellets",
    imgDay: "snow-rain.png",
    imgNight: "snow-rain.png",
    bg_night_from: "from-neutral-300",
    bg_night_to: "to-gray-700",
    bg_day_from: "from-neutral-300",
    bg_day_to: "to-gray-700",
    icon: 377,
  },
  {
    code: 1273,
    day: "Patchy light rain with thunder",
    night: "Patchy light rain with thunder",
    imgDay: "heavy-raining-and-thunder.png",
    imgNight: "heavy-raining-and-thunder.png",
    bg_night_from: "from-neutral-600",
    bg_night_to: "to-gray-800",
    bg_day_from: "from-neutral-600",
    bg_day_to: "to-gray-800",
    icon: 386,
  },
  {
    code: 1276,
    day: "Moderate or heavy rain with thunder",
    night: "Moderate or heavy rain with thunder",
    imgDay: "heavy-raining-and-thunder.png",
    imgNight: "heavy-raining-and-thunder.png",
    bg_night_from: "from-neutral-600",
    bg_night_to: "to-gray-800",
    bg_day_from: "from-neutral-600",
    bg_day_to: "to-gray-800",
    icon: 389,
  },
  {
    code: 1279,
    day: "Patchy light snow with thunder",
    night: "Patchy light snow with thunder",
    imgDay: "windy-lightning-snow-cloud.png",
    imgNight: "windy-lightning-snow-cloud.png",
    bg_night_from: "from-neutral-600",
    bg_night_to: "to-gray-800",
    bg_day_from: "from-neutral-600",
    bg_day_to: "to-gray-800",
    icon: 392,
  },
  {
    code: 1282,
    day: "Moderate or heavy snow with thunder",
    night: "Moderate or heavy snow with thunder",
    imgDay: "windy-lightning-snow-cloud.png",
    imgNight: "windy-lightning-snow-cloud.png",
    bg_night_from: "from-neutral-600",
    bg_night_to: "to-gray-800",
    bg_day_from: "from-neutral-600",
    bg_day_to: "to-gray-800",
    icon: 395,
  },
];
//bg-gradient-to-r from-red-500 to-yellow-300
